CREATE TYPE "roles" AS ENUM('guest', 'user', 'admin');--> statement-breakpoint
CREATE TYPE "mediaType" AS ENUM('video', 'photo');--> statement-breakpoint
CREATE TABLE "Users" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "Users_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" text,
	"uuid" text UNIQUE,
	"role" "roles" DEFAULT 'guest'::"roles",
	"timestamp" timestamp DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "Comments" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "Comments_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"parent_comment_id" integer,
	"commentor" integer,
	"actual_comment" text,
	"post_id" uuid,
	"updated" boolean,
	"timestamp" timestamp DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "Posts" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
	"user_poster" integer,
	"caption" text,
	"media_type" "mediaType",
	"upload_url" text,
	"category" text,
	"timestamp" timestamp DEFAULT now()
);
--> statement-breakpoint
CREATE INDEX "cat_index" ON "Posts" ("category");--> statement-breakpoint
CREATE INDEX "poster_index" ON "Posts" ("user_poster");--> statement-breakpoint
ALTER TABLE "Comments" ADD CONSTRAINT "Comments_parent_comment_id_Comments_id_fkey" FOREIGN KEY ("parent_comment_id") REFERENCES "Comments"("id");--> statement-breakpoint
ALTER TABLE "Comments" ADD CONSTRAINT "Comments_commentor_Users_id_fkey" FOREIGN KEY ("commentor") REFERENCES "Users"("id");--> statement-breakpoint
ALTER TABLE "Comments" ADD CONSTRAINT "Comments_post_id_Posts_id_fkey" FOREIGN KEY ("post_id") REFERENCES "Posts"("id");--> statement-breakpoint
ALTER TABLE "Posts" ADD CONSTRAINT "Posts_user_poster_Users_id_fkey" FOREIGN KEY ("user_poster") REFERENCES "Users"("id");